const fs = require('fs');
const path = require('path');

const entries = [
  {
    slug: 'jenis-jenis-demokrasi-dan-penerapannya-di-indonesia',
    title: 'Jenis-Jenis Demokrasi dan Penerapannya di Indonesia',
    desc: 'Sejarah penerapan tiga jenis demokrasi utama di Indonesia: Demokrasi Liberal, Demokrasi Terpimpin, dan Demokrasi Pancasila.',
    content: 'Jenis-jenis demokrasi yang pernah diterapkan di Indonesia memperlihatkan dinamika politik negara dalam mencari bentuk pemerintahan yang paling sesuai dengan kepribadian bangsa. Sepanjang sejarah pasca-kemerdekaan, sistem ini mengalami pasang surut. Buat kamu yang sering kebingungan membedakan ciri khas tiap eranya, TugasMu sebagai teman pintar belajar akan membedah fase transisi tersebut secara lengkap.\n\n## 1. Demokrasi Liberal (1950 - 1959)\nFase ini merupakan eksperimen pertama Indonesia dalam menerapkan sistem demokrasi ala Barat (parlementer) di bawah payung UUDS 1950.\n- **Karakteristik:** Multi-partai mutlak. Kabinet pemerintahan dipimpin oleh Perdana Menteri dan bertanggung jawab langsung kepada parlemen.\n- **Penerapan:** Kebebasan politik terjamin penuh, namun sistem ini gagal menciptakan stabilitas negara. Kabinet terus-menerus jatuh bangun karena mosi tidak percaya di parlemen, sehingga pembangunan ekonomi tersendat.\n\n## 2. Demokrasi Terpimpin (1959 - 1965)\nSistem ini lahir lewat Dekrit Presiden 5 Juli 1959 sebagai antitesis dari kekacauan sistem liberal. Demokrasi ini dipelopori langsung oleh Presiden Soekarno.\n- **Karakteristik:** Dominasi mutlak kekuasaan eksekutif (Presiden). Partai politik ditekan, sedangkan peran militer dan PKI menguat.\n- **Penerapan:** Istilah "Terpimpin" pada awalnya dimaknai sebagai kepemimpinan berdasarkan sila keempat Pancasila. Namun praktiknya, kekuasaan terpusat memunculkan penyimpangan konstitusi, seperti pengangkatan Soekarno sebagai Presiden seumur hidup.\n\n## 3. Demokrasi Pancasila (Orde Baru hingga Reformasi)\nSistem ini diberlakukan pasca runtuhnya Demokrasi Terpimpin, dan merupakan sistem tata negara yang secara resmi kita anut hingga hari ini.\n- **Karakteristik Dasar:** Mengutamakan musyawarah mufakat, keseimbangan hak dan kewajiban warga negara, serta menjunjung tinggi nilai-nilai Ketuhanan dan Kemanusiaan.\n- **Penerapan Era Orde Baru (1966-1998):** Secara retorika menggunakan asas Pancasila, namun dalam praktiknya kembali menjadi otoriter. Pemilu dikontrol ketat dan oposisi dibungkam.\n- **Penerapan Era Reformasi (1998-sekarang):** Demokrasi Pancasila dikembalikan ke jalur konstitusionalnya (berdasarkan amandemen UUD 1945). Terjadi kebebasan pers absolut, pemilihan umum presiden secara langsung, serta berlakunya desentralisasi daerah.\n\nMenganalisis jenis-jenis demokrasi yang pernah singgah di Indonesia adalah materi wajib ujian nasional. Ingat, sistem terbaik adalah yang selaras dengan nilai historis bangsa itu sendiri. Bimbingan AI dapat membantu kamu membuat peta pikiran (mind map) dari perubahan sistem politik ini.'
  },
  {
    slug: 'memahami-wawasan-nusantara-sebagai-geopolitik-indonesia',
    title: 'Memahami Wawasan Nusantara sebagai Geopolitik Indonesia',
    desc: 'Pengertian Wawasan Nusantara sebagai cara pandang bangsa Indonesia terhadap diri dan lingkungannya demi menjaga kedaulatan negara.',
    content: 'Memahami Wawasan Nusantara sebagai geopolitik Indonesia merupakan landasan penting agar warga negara memiliki kesadaran kolektif dalam menjaga keutuhan Negara Kesatuan Republik Indonesia (NKRI). Sebagai negara kepulauan terbesar di dunia, Indonesia rentan mengalami perpecahan jika cara pandang masyarakatnya bersifat kedaerahan. Oleh karena itu, TugasMu sebagai teman pintar belajar akan membedah konsep pemersatu bangsa ini.\n\n## Pengertian Wawasan Nusantara\nSecara etimologis, "wawasan" berarti cara tinjau atau pandangan, sedangkan "nusantara" adalah sebutan bagi kepulauan Indonesia. Wawasan Nusantara adalah cara pandang bangsa Indonesia terhadap diri dan lingkungannya berdasarkan Pancasila dan UUD 1945. \nKonsep utamanya adalah memandang seluruh kepulauan Indonesia (termasuk daratan, perairan, dan ruang udara di atasnya) sebagai satu kesatuan yang utuh (holistik), baik dari segi ideologi, politik, ekonomi, sosial-budaya, hingga pertahanan keamanan (Ipoleksosbudhankam).\n\n## Tujuan dan Fungsi Geopolitik\n- **Ke Luar:** Menjamin kepentingan nasional di era globalisasi dan ikut serta melaksanakan ketertiban dunia berdasarkan kemerdekaan dan perdamaian abadi.\n- **Ke Dalam:** Mewujudkan kesatuan dalam segenap aspek kehidupan nasional demi mencegah potensi separatisme atau disintegrasi bangsa.\n- **Fungsi Utama:** Sebagai pedoman, motivasi, dan rambu-rambu dalam menentukan segala kebijaksanaan pemerintah serta tindak-tanduk masyarakat sehari-hari.\n\n## Implementasi Wawasan Nusantara\nPenerapan geopolitik ini bukan sekadar tugas militer (TNI), melainkan tanggung jawab seluruh warga negara:\n- **Bidang Politik:** Memastikan setiap kebijakan pemerintah pusat adil bagi daerah terluar dan perbatasan, serta menjalankan pemilu secara demokratis.\n- **Bidang Ekonomi:** Pembangunan jalan tol antarprovinsi dan subsidi BBM satu harga untuk pemerataan kesejahteraan, sehingga seluruh kekayaan nusantara dinikmati secara kolektif.\n- **Bidang Sosial-Budaya:** Menghargai keragaman adat (Bhinneka Tunggal Ika) tanpa merendahkan suku lain, serta menjadikan kebudayaan lokal sebagai aset wisata nasional.\n\nMengaplikasikan ilmu Wawasan Nusantara di kehidupan sehari-hari (seperti tidak menyebarkan hoaks pemecah belah bangsa) adalah bentuk bela negara. Jika kamu butuh contoh studi kasus lebih banyak untuk bahan makalah, jangan ragu berdiskusi dengan Bimbingan AI.'
  },
  {
    slug: 'perbandingan-hak-dan-kewajiban-warga-negara-menurut-uud-1945',
    title: 'Perbandingan Hak dan Kewajiban Warga Negara Menurut UUD 1945',
    desc: 'Pelajari keseimbangan antara hak asasi manusia dan kewajiban warga negara yang dijamin oleh konstitusi UUD 1945.',
    content: 'Perbandingan hak dan kewajiban warga negara menurut UUD 1945 merefleksikan konsep keadilan yang dianut oleh negara Indonesia, di mana kebebasan individu tidak boleh melanggar hak orang lain maupun ketertiban umum. Keseimbangan ini sering ditanyakan dalam soal esai PPKn. Agar kamu mudah memetakan pasalnya, mari kita buat perbandingan komprehensif bersama Bimbingan AI TugasMu sebagai teman pintar belajar.\n\n## Daftar Hak Warga Negara\nHak adalah sesuatu yang mutlak menjadi milik seseorang dan penggunanya bergantung pada individu tersebut. UUD 1945 memberikan jaminan konstitusional yang kuat, di antaranya:\n- **Hak atas Kedudukan Hukum yang Sama:** Setiap warga negara bersamaan kedudukannya di dalam hukum dan pemerintahan (Pasal 27 ayat 1).\n- **Hak atas Pekerjaan dan Penghidupan yang Layak:** Dijamin secara jelas dalam Pasal 27 ayat 2.\n- **Hak Kemerdekaan Beragama:** Negara membebaskan setiap penduduk untuk memeluk agama dan beribadat menurut kepercayaannya (Pasal 29 ayat 2).\n- **Hak Mendapat Pendidikan:** Setiap warga negara berhak untuk mengeyam pendidikan dan pemerintah wajib membiayainya (Pasal 31 ayat 1 dan 2).\n\n## Daftar Kewajiban Warga Negara\nKewajiban adalah tindakan yang harus dilakukan oleh warga negara berdasarkan ketentuan hukum yang berlaku. Jika tidak dilakukan, maka individu tersebut akan dijatuhi sanksi pidana/perdata.\n- **Kewajiban Taat Hukum:** Wajib menjunjung hukum dan pemerintahan tanpa kecualinya (Pasal 27 ayat 1).\n- **Kewajiban Membela Negara:** Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara (Pasal 27 ayat 3).\n- **Kewajiban Menghormati HAM Orang Lain:** Wajib tunduk kepada pembatasan yang ditetapkan undang-undang demi menghormati hak orang lain (Pasal 28J ayat 1 dan 2).\n- **Kewajiban Mengikuti Pendidikan Dasar:** Kewajiban yang selaras dengan hak pendidikan dasar dari pemerintah (Pasal 31 ayat 2).\n\n## Keseimbangan Hak dan Kewajiban\nDalam ideologi liberalisme, hak individu diutamakan. Namun dalam ideologi Pancasila, terdapat asas keseimbangan. Seseorang tidak bisa menuntut haknya atas fasilitas negara (seperti jalan raya atau keamanan polisi) jika ia mangkir dari kewajibannya (seperti membayar pajak yang diatur dalam Pasal 23A).\n\nMenganalisis pelanggaran konstitusi bermula dari kegagalan memahami perbedaan hak dan kewajiban warga negara ini. Untuk menguji daya ingatmu terkait pasal-pasal di atas, cobalah simulasi generator kuis dari TugasMu.'
  },
  {
    slug: 'jenis-ancaman-terhadap-integrasi-nasional-dan-mengatasinya',
    title: 'Jenis Ancaman terhadap Integrasi Nasional dan Cara Mengatasinya',
    desc: 'Penjelasan mengenai bentuk ancaman militer dan non-militer terhadap integrasi nasional Indonesia serta strategi pencegahannya.',
    content: 'Jenis ancaman terhadap integrasi nasional mencakup spektrum yang sangat luas di era globalisasi modern, bergeser dari sekadar invasi militer klasik menuju perang proksi yang merusak ideologi negara secara kasat mata. Menjaga keutuhan Republik Indonesia adalah materi wajib dalam pelajaran kewarganegaraan. Lewat rangkuman dari Bimbingan AI TugasMu sebagai teman pintar belajar, mari kita bedah bentuk ancaman ini dan solusinya.\n\n## 1. Ancaman Militer\nAncaman militer adalah bentuk ancaman menggunakan kekuatan bersenjata dan terorganisasi yang membahayakan kedaulatan negara dan keselamatan segenap bangsa.\n- **Bentuk Ancaman:** Invasi militer (agresi) dari negara asing, pemberontakan bersenjata (separatisme seperti OPM), spionase (pencurian rahasia militer), sabotase objek vital nasional, dan aksi terorisme internasional.\n- **Cara Mengatasi:** Mengandalkan Tentara Nasional Indonesia (TNI) sebagai komponen utama pertahanan negara, serta Polri untuk keamanan internal. Pemerintah juga menerapkan sistem Sishankamrata (Sistem Pertahanan dan Keamanan Rakyat Semesta) di mana masyarakat dilibatkan sebagai komponen cadangan bela negara.\n\n## 2. Ancaman Non-Militer (Nirmiliter)\nAncaman non-militer memiliki karakteristik tidak berwujud fisik (tidak menggunakan senjata api), namun daya hancurnya bisa melumpuhkan negara dari dalam.\n- **Ancaman Ideologi:** Masuknya paham radikalisme, komunisme, atau liberalisme sekuler yang bertentangan dengan Pancasila.\n- **Ancaman Politik:** Praktik intimidasi dari negara *superpower*, atau oligarki di dalam negeri yang memicu ketidakpercayaan publik terhadap pemerintah (demonstrasi anarkis).\n- **Ancaman Ekonomi:** Dominasi produk impor, inflasi tinggi, ketergantungan pada utang luar negeri, dan kemiskinan struktural.\n- **Ancaman Sosial-Budaya:** Konsumerisme, gaya hidup kebarat-baratan (westernisasi), memudarnya sifat gotong-royong, serta invasi budaya asing yang merusak moral generasi muda (seperti peredaran narkoba global).\n\n## Peran Siswa dalam Menjaga Integrasi\nLalu apa tugasmu sebagai pelajar? Menangkal ancaman non-militer dimulai dari filter literasi digital (tidak menyebarkan hoaks pemecah belah SARA di media sosial), mencintai produk dalam negeri, dan berprestasi di kancah internasional untuk menaikkan nilai tawar diplomasi Indonesia.\n\nMemahami perbedaan antara ancaman militer dan ideologi akan sangat membantu kamu membuat esai bela negara yang tajam. Manfaatkan fitur pembuat makalah AI jika kamu ingin membedah salah satu kasus separatisme lebih mendalam.'
  },
  {
    slug: 'daftar-lembaga-negara-di-indonesia-dan-tugasnya',
    title: 'Daftar Lembaga-Lembaga Negara di Indonesia dan Tugasnya',
    desc: 'Rangkuman lengkap wewenang dan tugas lembaga eksekutif, legislatif, dan yudikatif berdasarkan UUD 1945 pasca-amandemen.',
    content: 'Daftar lembaga-lembaga negara di Indonesia mengalami perombakan arsitektur yang sangat signifikan pasca-amandemen UUD 1945 (1999-2002) guna menciptakan sistem pemisahan kekuasaan (*check and balances*) yang transparan dan anti-diktator. Kalau kamu masih bingung siapa yang bikin undang-undang dan siapa yang menghukum koruptor, TugasMu sebagai teman pintar belajar merangkum tupoksi (tugas pokok dan fungsi) setiap pilarnya.\n\n## 1. Lembaga Eksekutif (Pelaksana Undang-Undang)\nLembaga ini bertugas menjalankan roda pemerintahan negara sehari-hari.\n- **Presiden dan Wakil Presiden:** Pemegang kekuasaan tertinggi dalam mengelola negara, dibantu oleh para menteri kabinet. Presiden juga memegang kekuasaan tertinggi atas Angkatan Darat, Laut, dan Udara (Panglima Tertinggi).\n- **Kementerian Negara:** Organisasi pemerintah yang membidangi urusan tertentu dalam pemerintahan, di mana menterinya ditunjuk langsung dan bertanggung jawab kepada Presiden.\n\n## 2. Lembaga Legislatif (Pembuat Undang-Undang)\nLembaga ini merupakan representasi langsung dari suara rakyat.\n- **Majelis Permusyawaratan Rakyat (MPR):** Gabungan dari anggota DPR dan DPD. MPR bertugas melantik Presiden dan Wakil Presiden, serta satu-satunya lembaga yang berhak mengubah UUD 1945.\n- **Dewan Perwakilan Rakyat (DPR):** Lembaga pembuat undang-undang (Fungsi Legislasi), penyusun anggaran APBN (Fungsi Anggaran), dan pengawas kinerja pemerintah (Fungsi Pengawasan).\n- **Dewan Perwakilan Daerah (DPD):** Perwakilan daerah otonom yang bertugas mengajukan dan membahas RUU yang berkaitan dengan otonomi daerah.\n\n## 3. Lembaga Yudikatif (Penegak Hukum dan Undang-Undang)\nLembaga ini bertugas mengawasi agar penegakan hukum di Indonesia berjalan adil dan konstitusional.\n- **Mahkamah Agung (MA):** Pemegang kekuasaan kehakiman tertinggi. Mengadili perkara pada tingkat kasasi dan menguji peraturan perundang-undangan di bawah undang-undang.\n- **Mahkamah Konstitusi (MK):** Bertugas menguji undang-undang terhadap UUD 1945 (*judicial review*), memutus sengketa kewenangan antar-lembaga negara, membubarkan partai politik, serta memutus sengketa hasil pemilu.\n- **Komisi Yudisial (KY):** Lembaga independen yang bertugas menjaga kehormatan dan keluhuran martabat hakim agung, serta mengusulkan pengangkatan hakim agung baru kepada DPR.\n\n## 4. Lembaga Eksaminatif\n- **Badan Pemeriksa Keuangan (BPK):** Bertugas memeriksa pengelolaan dan tanggung jawab atas keuangan negara (APBN/APBD) secara independen dan bebas dari intervensi pemerintah.\n\nDengan menghafal struktur tugas dari daftar lembaga negara di atas, tugas analisis hukum tatanegaramu akan terstruktur dengan sempurna. Kamu bisa meminta bimbingan AI untuk membandingkan lembaga ini dengan sistem tata negara di negara lain.'
  }
];

const DIR = path.join(__dirname, '../frontend/src/content/blog/ppkn');
if (!fs.existsSync(DIR)) fs.mkdirSync(DIR, { recursive: true });

entries.forEach(entry => {
  const fileContent = `---
title: "${entry.title}"
description: "${entry.desc}"
date: "2026-10-01T04:20:00Z"
kategori: "ppkn"
---

${entry.content}
`;
  const filePath = path.join(DIR, `${entry.slug}.mdx`);
  fs.writeFileSync(filePath, fileContent);
  console.log(`Generated: ${entry.slug}`);
});
