const fs = require('fs');
const path = require('path');

const entries = [
  {
    slug: 'daftar-organisasi-pergerakan-nasional-indonesia',
    title: 'Daftar Organisasi Pergerakan Nasional di Indonesia',
    desc: 'Pelajari daftar organisasi pergerakan nasional yang menjadi pelopor kemerdekaan Indonesia seperti Budi Utomo dan Sarekat Islam.',
    content: 'Daftar organisasi pergerakan nasional di Indonesia menjadi tonggak awal kebangkitan kesadaran berbangsa yang dipelopori oleh kaum intelektual. Berbeda dengan era perang daerah, masa ini menggunakan diplomasi, pendidikan, dan pers sebagai senjata utama. Kalau kamu sedang bersiap ujian sejarah, TugasMu sebagai teman pintar belajar akan merangkumkan daftar organisasi kuncinya.\n\n## 1. Budi Utomo (1908)\nBudi Utomo didirikan pada tanggal 20 Mei 1908 oleh Dr. Sutomo dan mahasiswa STOVIA (Sekolah Kedokteran Jawa). Organisasi ini merupakan pelopor pergerakan nasional pertama di Indonesia, dengan fokus awal pada kemajuan pendidikan dan kebudayaan di Jawa dan Madura. Tanggal berdirinya Budi Utomo kemudian diperingati sebagai Hari Kebangkitan Nasional.\n\n## 2. Sarekat Islam (1912)\nBerawal dari Sarekat Dagang Islam (SDI) yang didirikan oleh K.H. Samanhudi pada 1905, organisasi ini bertransformasi menjadi Sarekat Islam (SI) di bawah kepemimpinan H.O.S. Tjokroaminoto. SI berubah menjadi organisasi massa politik terbesar pada masanya yang berjuang membela hak-hak ekonomi rakyat pribumi melawan monopoli pedagang asing.\n\n## 3. Indische Partij (1912)\nIndische Partij adalah partai politik pertama di Hindia Belanda yang didirikan oleh Tiga Serangkai: E.F.E. Douwes Dekker (Danudirja Setiabudi), Tjipto Mangoenkoesoemo, dan Suwardi Suryaningrat (Ki Hajar Dewantara). Ini adalah organisasi pertama yang secara terang-terangan menuntut kemerdekaan penuh bagi Indonesia.\n\n## 4. Partai Nasional Indonesia / PNI (1927)\nPNI didirikan oleh Ir. Soekarno di Bandung dengan asas Marhaenisme. Organisasi ini mengadopsi sikap non-kooperatif (menolak bekerja sama dengan pemerintah kolonial Belanda) dan secara agresif menuntut kemerdekaan politik dan ekonomi secara mandiri.\n\nMemahami corak dan tujuan dari setiap daftar organisasi pergerakan nasional ini akan sangat membantu tugas analisis sejarahmu. Jangan lupa gunakan fitur Bimbingan AI untuk membuat ringkasan yang lebih padat.'
  },
  {
    slug: 'masa-pendudukan-jepang-di-indonesia-1942-1945',
    title: 'Masa Pendudukan Jepang di Indonesia (1942-1945)',
    desc: 'Sejarah lengkap masa pendudukan Jepang di Indonesia, organisasi bentukan Jepang, dan penderitaan rakyat melalui Romusha.',
    content: 'Masa pendudukan Jepang di Indonesia (1942-1945) meski berlangsung sangat singkat, meninggalkan dampak perubahan militer dan sosial yang sangat masif dibandingkan penjajahan Belanda. Buat kamu yang butuh referensi untuk tugas sejarah, mari kita bedah strategi Jepang menarik simpati hingga praktik eksploitasi mereka. TugasMu, teman pintar belajar, siap memandu.\n\n## Latar Belakang Masuknya Jepang\nJepang mendarat pertama kali di Tarakan (Kalimantan Timur) pada Januari 1942 dengan tujuan utama menguasai sumber daya minyak untuk mendukung Perang Asia Timur Raya. Pada tanggal 8 Maret 1942, Belanda secara resmi menyerah tanpa syarat kepada Jepang melalui Perjanjian Kalijati. Jepang mempropagandakan diri sebagai "Saudara Tua" yang akan membebaskan Asia dari penjajahan Barat lewat semboyan Gerakan Tiga A.\n\n## Organisasi Bentukan Jepang\nUntuk memobilisasi tenaga rakyat Indonesia demi kepentingan perangnya, Jepang membentuk berbagai organisasi semi-militer dan militer, antara lain:\n- **Putera (Pusat Tenaga Rakyat):** Dipimpin oleh Empat Serangkai (Soekarno, Hatta, Ki Hajar Dewantara, KH Mas Mansyur) dengan tujuan awal membantu Jepang, namun akhirnya digunakan tokoh nasional untuk memupuk nasionalisme.\n- **PETA (Pembela Tanah Air):** Organisasi militer bersenjata yang dilatih langsung oleh tentara Jepang. PETA kelak menjadi cikal bakal Tentara Nasional Indonesia (TNI).\n- **Seinendan dan Keibodan:** Barisan pemuda dan pembantu polisi untuk menjaga keamanan garis belakang.\n\n## Romusha dan Perlawanan Rakyat\nDi balik propaganda manis, Jepang menerapkan sistem kerja paksa yang disebut Romusha. Ratusan ribu rakyat Indonesia dipaksa membangun benteng, jalan, dan rel kereta api dalam kondisi kelaparan yang ekstrem. Penderitaan ini memicu perlawanan lokal bersenjata, seperti Perlawanan PETA di Blitar yang dipimpin oleh Supriyadi, serta perlawanan di Singaparna dan Indramayu.\n\nMembedah masa pendudukan Jepang di Indonesia memberikan wawasan tentang akar struktur militer negara kita. Kamu bisa manfaatkan bimbingan AI untuk menyusun esai perbandingan masa penjajahan ini.'
  },
  {
    slug: 'detik-detik-proklamasi-kemerdekaan-indonesia',
    title: 'Detik-detik Peristiwa Proklamasi Kemerdekaan Indonesia 17 Agustus 1945',
    desc: 'Kronologi lengkap detik-detik proklamasi kemerdekaan Indonesia mulai dari Rengasdengklok hingga pembacaan teks proklamasi.',
    content: 'Detik-detik peristiwa proklamasi kemerdekaan Indonesia 17 Agustus 1945 merupakan titik kulminasi dari perjuangan panjang bangsa Indonesia melawan kolonialisme. Proses transisi kekuasaan ini berlangsung dalam tensi tinggi karena kekosongan kekuasaan (vacuum of power) usai Jepang menyerah kepada Sekutu. Bersama TugasMu sebagai teman pintar belajar, mari kita urutkan kronologinya.\n\n## Peristiwa Rengasdengklok (16 Agustus 1945)\nSetelah mendengar berita kekalahan Jepang pada 14 Agustus 1945, golongan muda (seperti Sukarni, Wikana, dan Chaerul Saleh) mendesak Soekarno dan Hatta agar segera memproklamasikan kemerdekaan. Namun, golongan tua menolak karena ingin menunggu keputusan PPKI agar tidak terjadi pertumpahan darah. Akhirnya, pada 16 Agustus dini hari, golongan muda "menculik" Soekarno-Hatta ke Rengasdengklok, Karawang, untuk menjauhkan mereka dari pengaruh militer Jepang dan memaksa agar proklamasi segera dilaksanakan.\n\n## Perumusan Teks Proklamasi\nSetelah tercapai kesepakatan antara Ahmad Subardjo (mewakili golongan tua) dan golongan muda, Soekarno-Hatta kembali ke Jakarta. Perumusan teks proklamasi dilakukan pada malam harinya di rumah Laksamana Maeda, seorang perwira angkatan laut Jepang yang bersimpati pada perjuangan Indonesia. Teks tersebut dirumuskan oleh Soekarno, Hatta, dan Ahmad Subardjo, lalu diketik secara resmi oleh Sayuti Melik.\n\n## Pembacaan Teks Proklamasi (17 Agustus 1945)\nPada hari Jumat, 17 Agustus 1945, pukul 10.00 WIB, naskah proklamasi dibacakan secara khidmat oleh Ir. Soekarno didampingi Drs. Moh. Hatta di kediaman Soekarno, Jalan Pegangsaan Timur No. 56, Jakarta. Acara dilanjutkan dengan pengibaran bendera Merah Putih yang dijahit oleh Ibu Fatmawati, diiringi lagu kebangsaan Indonesia Raya.\n\nMengetahui alur detik-detik peristiwa proklamasi kemerdekaan Indonesia akan membantu kamu menjawab soal ujian berbasis kronologi. Gunakan Bimbingan AI untuk mengasah hafalan tahun dan tokoh penting dari peristiwa ini.'
  },
  {
    slug: 'perjuangan-mempertahankan-kemerdekaan-diplomasi-dan-fisik',
    title: 'Perjuangan Mempertahankan Kemerdekaan: Jalur Diplomasi dan Fisik',
    desc: 'Pelajari sejarah perjuangan mempertahankan kemerdekaan Indonesia melalui kombinasi jalur pertempuran fisik dan perundingan diplomasi.',
    content: 'Perjuangan mempertahankan kemerdekaan Indonesia dilakukan melalui kombinasi jalur diplomasi di meja perundingan dan jalur perlawanan fisik bersenjata di lapangan. Setelah merdeka pada tahun 1945, ancaman terbesar datang dari tentara Sekutu yang ditumpangi oleh NICA (Belanda) yang ingin kembali menjajah. Buat tugas sejarahmu makin berbobot, TugasMu sebagai teman pintar belajar merangkum dua strategi utama tersebut.\n\n## Jalur Perjuangan Fisik (Bersenjata)\nKetika Belanda mencoba memaksakan kekuasaan militer, rakyat dan Tentara Keamanan Rakyat (TKR) merespons dengan pertempuran berdarah di berbagai wilayah.\n- **Pertempuran Surabaya (10 November 1945):** Pertempuran sipil terbesar melawan tentara Inggris yang dipicu oleh tewasnya Jenderal Mallaby. Bung Tomo membakar semangat rakyat melalui pidato radionya.\n- **Palagan Ambarawa (Desember 1945):** Dipimpin oleh Kolonel Sudirman, TKR berhasil memukul mundur pasukan Sekutu menggunakan taktik gelar supit urang (pengepungan ganda).\n- **Bandung Lautan Api (Maret 1946):** Rakyat dan tentara sengaja membumihanguskan wilayah Bandung Selatan agar fasilitas kota tidak bisa digunakan sebagai markas militer Sekutu.\n\n## Jalur Perjuangan Diplomasi\nSelain perang terbuka, pemerintah Indonesia terus memperjuangkan pengakuan kedaulatan di mata hukum internasional melalui serangkaian perundingan.\n- **Perjanjian Linggarjati (1946):** Pengakuan de facto Belanda atas wilayah Republik Indonesia yang hanya mencakup Jawa, Sumatera, dan Madura.\n- **Perjanjian Renville (1948):** Perjanjian yang sangat merugikan Indonesia karena wilayahnya semakin menyempit berdasarkan Garis van Mook, menyusul Agresi Militer Belanda I.\n- **Perjanjian Roem-Royen (1949):** Titik terang kembalinya pemerintahan Indonesia ke Yogyakarta pasca Agresi Militer Belanda II.\n- **Konferensi Meja Bundar / KMB (1949):** Puncak diplomasi di Den Haag, di mana Belanda akhirnya mengakui kedaulatan Indonesia secara penuh dalam bentuk Republik Indonesia Serikat (RIS).\n\nMenganalisis sejarah perjuangan mempertahankan kemerdekaan Indonesia membutuhkan pemahaman bahwa militer dan diplomasi adalah dua sayap yang tidak terpisahkan. Kamu bisa mencoba generator soal sejarah dari Bimbingan AI untuk menguji wawasanmu tentang materi ini.'
  },
  {
    slug: 'sejarah-masa-demokrasi-liberal-dan-terpimpin',
    title: 'Sejarah Masa Demokrasi Liberal dan Terpimpin di Indonesia',
    desc: 'Perbandingan sejarah dinamika politik dan ekonomi pada era Demokrasi Liberal dan Demokrasi Terpimpin di bawah Presiden Soekarno.',
    content: 'Sejarah masa demokrasi liberal dan terpimpin di Indonesia merepresentasikan dua eksperimen sistem tata negara yang saling bertolak belakang pada era pemerintahan Presiden Soekarno. Periode ini diwarnai instabilitas kabinet, gejolak ideologi, hingga lahirnya dekrit presiden. Jika kamu merasa kesulitan merangkum timeline periode ini, TugasMu sebagai teman pintar belajar siap membantu.\n\n## Masa Demokrasi Liberal (1950 - 1959)\nPada masa ini, Indonesia menganut sistem pemerintahan parlementer yang berlandaskan pada UUDS 1950. \n- **Dinamika Politik:** Ditandai dengan penerapan sistem multipartai absolut. Kekuasaan pemerintah dipegang oleh Perdana Menteri, sementara Presiden hanya bertindak sebagai simbol negara. \n- **Instabilitas:** Karena tidak ada partai mayoritas yang dominan, kabinet sangat mudah jatuh lewat mosi tidak percaya. Dalam kurun waktu 9 tahun, terjadi pergantian kabinet sebanyak 7 kali (Kabinet Natsir, Sukiman, Wilopo, hingga Djuanda). \n- **Prestasi:** Keberhasilan menyelenggarakan Pemilu pertama yang paling demokratis pada tahun 1955, serta penyelenggaraan Konferensi Asia-Afrika (KAA) di Bandung.\n\n## Dekrit Presiden 5 Juli 1959\nKegagalan Dewan Konstituante dalam merumuskan UUD baru ditambah krisis politik dan keamanan di daerah, membuat Presiden Soekarno mengeluarkan Dekrit Presiden 1959. Isinya: membubarkan Konstituante, kembali ke UUD 1945, dan membentuk MPRS serta DPAS. Dekrit ini menjadi jembatan pergantian sistem menuju Demokrasi Terpimpin.\n\n## Masa Demokrasi Terpimpin (1959 - 1965)\nEra ini membalikkan keadaan; kekuasaan negara terpusat sepenuhnya di tangan Presiden (eksekutif).\n- **Dinamika Politik:** Presiden Soekarno mengenalkan konsep Nasakom (Nasionalis, Agama, Komunis) untuk menyatukan kekuatan ideologi yang berkonflik. Pembatasan ruang gerak partai politik diberlakukan secara ketat.\n- **Kebijakan Luar Negeri:** Indonesia mengambil sikap anti-imperialisme radikal, keluar dari PBB, serta melancarkan konfrontasi Dwikora melawan pembentukan Federasi Malaysia.\n- **Krisis Ekonomi:** Fokus berlebihan pada proyek mercusuar (seperti pembangunan Monas dan GBK) serta inflasi yang menembus ratusan persen membuat kondisi ekonomi rakyat merosot tajam.\n\nMembaca sejarah masa demokrasi liberal dan terpimpin di Indonesia memperlihatkan bagaimana negara muda mencari bentuk pemerintahan idealnya. Agar lebih paham, kamu bisa meminta Bimbingan AI untuk membuatkan tabel perbandingan detail dari kedua era tersebut.'
  }
];

const DIR = path.join(__dirname, '../frontend/src/content/blog/sejarah');
if (!fs.existsSync(DIR)) fs.mkdirSync(DIR, { recursive: true });

entries.forEach(entry => {
  const fileContent = `---
title: "${entry.title}"
description: "${entry.desc}"
date: "2026-10-01T04:00:00Z"
kategori: "sejarah"
---

${entry.content}
`;
  const filePath = path.join(DIR, `${entry.slug}.mdx`);
  fs.writeFileSync(filePath, fileContent);
  console.log(`Generated: ${entry.slug}`);
});
