const fs = require('fs');
const path = require('path');

const entries = [
  {
    slug: 'sejarah-masa-orde-baru-lahir-perkembangan-keruntuhan',
    title: 'Sejarah Masa Orde Baru: Lahir, Perkembangan, dan Keruntuhannya',
    desc: 'Ulasan lengkap mengenai sejarah rezim Orde Baru di bawah pimpinan Soeharto, dari pembangunan ekonomi hingga Krisis Moneter 1998.',
    content: 'Sejarah masa orde baru menggambarkan era pemerintahan terlama di Indonesia yang dipimpin oleh Presiden Soeharto selama 32 tahun. Rezim ini fokus pada stabilitas politik dan pembangunan ekonomi sebagai antitesis dari gejolak politik era sebelumnya. Buat kamu yang sedang mempelajari bab sejarah politik kontemporer, Bimbingan AI TugasMu sebagai teman pintar belajar telah merangkum siklus lahir, berkembang, hingga runtuhnya era ini.\n\n## Lahirnya Orde Baru (Transisi Kekuasaan)\nKelahiran Orde Baru dipicu oleh peristiwa berdarah Gerakan 30 September (G30S/PKI) tahun 1965 yang menciptakan krisis keamanan. Titik balik resminya ditandai dengan diterbitkannya Surat Perintah Sebelas Maret (Supersemar) pada tahun 1966. Melalui surat tersebut, Presiden Soekarno memberi mandat kepada Letjen Soeharto untuk memulihkan keamanan. Mandat ini kelak menjadi kendaraan politik Soeharto untuk membubarkan PKI dan secara perlahan mengambil alih kekuasaan eksekutif.\n\n## Perkembangan dan Pembangunan Ekonomi\nOrde Baru mencanangkan Rencana Pembangunan Lima Tahun (Repelita) yang menitikberatkan pada sektor pertanian dan infrastruktur. \n- **Swasembada Pangan:** Pada tahun 1984, Indonesia berhasil mencapai swasembada beras dan mendapatkan penghargaan dari FAO.\n- **Stabilitas Politik:** Pemerintah membatasi kebebasan pers, mewajibkan asas tunggal Pancasila, dan menyederhanakan (fusi) partai politik menjadi hanya tiga partai: Golkar, PPP, dan PDI.\n- **Pertumbuhan Terpusat:** Meski ekonomi tumbuh pesat, pembangunan sangat terpusat (Jawasentris) dan marak diwarnai praktik Korupsi, Kolusi, dan Nepotisme (KKN).\n\n## Keruntuhan Orde Baru (Krisis 1998)\nFondasi ekonomi semu Orde Baru hancur lebur akibat hantaman Krisis Moneter Asia pada pertengahan tahun 1997. Nilai tukar Rupiah anjlok, harga sembako meroket, dan pengangguran meningkat tajam. Kondisi ini memicu gelombang demonstrasi mahasiswa besar-besaran di berbagai daerah (Gerakan Reformasi).\n\nTragedi penembakan mahasiswa Universitas Trisakti pada 12 Mei 1998 menyulut kerusuhan massal di Jakarta. Kehilangan dukungan dari militer, menteri-menterinya, dan rakyat, Presiden Soeharto akhirnya menyatakan berhenti dari jabatannya pada tanggal 21 Mei 1998, menandai berakhirnya rezim Orde Baru.\n\nMemahami sejarah masa orde baru membutuhkan pandangan yang objektif untuk melihat sisi kelam dan pencapaiannya. Jika butuh ringkasan poin-poin krusial, kamu bisa memanfaatkan fitur rangkuman AI dari TugasMu.'
  },
  {
    slug: 'perbandingan-revolusi-amerika-prancis-rusia',
    title: 'Perbandingan Revolusi Amerika, Prancis, dan Rusia',
    desc: 'Analisis perbandingan latar belakang, ideologi, dan dampak dari tiga revolusi besar dunia: Amerika, Prancis, dan Rusia.',
    content: 'Perbandingan revolusi Amerika, Prancis, dan Rusia memberikan wawasan bagaimana ideologi hak asasi manusia, demokrasi, dan sosialisme meruntuhkan sistem monarki absolut di dunia. Ketiga peristiwa bersejarah ini saling berkaitan dan sangat memengaruhi kebangkitan pergerakan nasional di Indonesia. TugasMu sebagai teman pintar belajar merangkumkan inti komparasinya agar tugas analisis sejarahmu makin tajam.\n\n## 1. Revolusi Amerika (1775 - 1783)\n- **Latar Belakang:** Penolakan 13 koloni Inggris di Amerika Utara terhadap beban pajak yang tidak adil tanpa perwakilan di parlemen (*"No Taxation without Representation"*).\n- **Tokoh Utama:** George Washington, Thomas Jefferson.\n- **Ideologi & Sifat:** Liberalisme dan Demokrasi. Perang ini murni bersifat kemerdekaan koloni lepas dari negara induk.\n- **Dampak Global:** Melahirkan negara Republik demokratis pertama di dunia dan deklarasi hak asasi (*Declaration of Independence*).\n\n## 2. Revolusi Prancis (1789 - 1799)\n- **Latar Belakang:** Ketimpangan sosial ekstrem antara rakyat jelata yang kelaparan dengan gaya hidup mewah Raja Louis XVI dan kaum bangsawan (feodalisme).\n- **Tokoh Utama:** Maximilien Robespierre, Napoleon Bonaparte.\n- **Ideologi & Sifat:** Nasionalisme, Kebebasan, Kesetaraan (*Liberté, Égalité, Fraternité*). Revolusi ini adalah perlawanan rakyat terhadap rajanya sendiri secara brutal (menggunakan *guillotine*).\n- **Dampak Global:** Menghancurkan monarki absolut di Eropa dan memunculkan kesadaran tentang kedaulatan rakyat serta hak asasi manusia.\n\n## 3. Revolusi Rusia (1917)\n- **Latar Belakang:** Penderitaan kaum buruh dan petani akibat pemerintahan Tsar Nicholas II yang diktator, diperparah oleh krisis ekonomi akibat Perang Dunia I.\n- **Tokoh Utama:** Vladimir Lenin (Bolshevik).\n- **Ideologi & Sifat:** Marxisme-Komunisme. Revolusi kelas di mana kaum buruh (proletar) menggulingkan sistem kapitalis dan feodal.\n- **Dampak Global:** Melahirkan Uni Soviet sebagai negara komunis pertama di dunia, yang memicu terjadinya Perang Dingin di kemudian hari.\n\n## Tabel Perbandingan\n\n| Aspek | Amerika (1776) | Prancis (1789) | Rusia (1917) |\n| :--- | :--- | :--- | :--- |\n| **Pemicu Utama** | Pajak kolonial | Ketimpangan ekonomi | Penindasan buruh/petani |\n| **Target Guling** | Raja Inggris (eksternal) | Raja Louis XVI (internal) | Tsar Rusia (internal) |\n| **Ideologi Lahir** | Demokrasi Liberal | Republik Konstitusional | Komunisme-Sosialisme |\n\nMenganalisis perbandingan revolusi Amerika, Prancis, dan Rusia membuktikan bahwa ideologi kebebasan bisa dieksekusi dengan berbagai metode. Manfaatkan Bimbingan AI untuk melihat langsung efek ketiga revolusi ini terhadap berdirinya organisasi Boedi Oetomo dan Sarekat Islam.'
  },
  {
    slug: 'sejarah-perang-dunia-i-dan-ii-serta-dampak-globalnya',
    title: 'Sejarah Perang Dunia I dan II serta Dampak Globalnya',
    desc: 'Pemahaman komprehensif mengenai sebab umum dan khusus, poros aliansi, serta dampak global dari Perang Dunia I dan Perang Dunia II.',
    content: 'Sejarah Perang Dunia I dan II serta dampak globalnya adalah fondasi utama untuk memahami terbentuknya peta geopolitik dunia modern dan berdirinya Perserikatan Bangsa-Bangsa (PBB). Dua konflik destruktif ini mengubah tata dunia dari sistem imperialisme tradisional menjadi era negara-negara merdeka. Bersama Bimbingan AI TugasMu sebagai teman pintar belajar, mari kita bedah perbedaan pemicu dari kedua perang besar ini.\n\n## Perang Dunia I (1914 - 1918)\nPD I adalah perang parit yang berpusat di Eropa, dipicu oleh persaingan industri, militerisme, dan politik aliansi rahasia antar-kekaisaran tua.\n- **Sebab Khusus:** Terbunuhnya Pangeran Franz Ferdinand (pewaris takhta Austria-Hongaria) di Sarajevo oleh nasionalis Serbia, Gavrilo Princip, pada 28 Juni 1914.\n- **Pihak Terlibat:** Blok Sentral (Jerman, Austria-Hongaria, Kesultanan Utsmaniyah) melawan Blok Sekutu (Inggris, Prancis, Rusia).\n- **Dampak Utama:** Runtuhnya 4 kekaisaran besar (Rusia, Jerman, Austria-Hongaria, Utsmaniyah), terbentuknya organisasi LBB (Liga Bangsa-Bangsa), dan lahirnya Traktat Versailles yang sangat merugikan pihak Jerman.\n\n## Perang Dunia II (1939 - 1945)\nBerbeda dengan PD I, Perang Dunia II memiliki skala kehancuran yang jauh lebih masif karena penggunaan teknologi persenjataan modern (pesawat tempur, tank, bom atom) dan meluas hingga ke benua Asia-Pasifik.\n- **Sebab Khusus:** Di Eropa, dipicu oleh invasi Jerman (dipimpin Adolf Hitler) ke Polandia pada 1 September 1939. Di Asia-Pasifik, dipicu oleh serangan kejutan pesawat Jepang ke pangkalan militer AS di Pearl Harbor pada 7 Desember 1941.\n- **Pihak Terlibat:** Blok Poros (Jerman Nazi, Italia Fasis, Kekaisaran Jepang) melawan Blok Sekutu (Inggris, AS, Uni Soviet, Tiongkok).\n- **Dampak Utama:** Lahirnya PBB, berakhirnya imperialisme klasik (memberi jalan bagi negara-negara Asia-Afrika untuk merdeka, termasuk Indonesia), dan kebangkitan Amerika Serikat serta Uni Soviet sebagai dua negara adidaya yang memicu Perang Dingin.\n\nMembaca sejarah perang dunia I dan II membantu kamu memahami mengapa dunia membutuhkan hukum internasional demi menghindari perang nuklir. Gunakan *tools* pembuat rangkuman TugasMu untuk menyederhanakan rentetan tanggal peperangan ini.'
  },
  {
    slug: 'perang-dingin-blok-barat-blok-timur-peran-indonesia',
    title: 'Perang Dingin: Blok Barat, Blok Timur, dan Peran Indonesia',
    desc: 'Konflik ideologi antara Amerika Serikat dan Uni Soviet, serta sikap independen Indonesia melalui Gerakan Non-Blok (GNB).',
    content: 'Perang Dingin antara Blok Barat dan Blok Timur adalah konflik perebutan hegemoni global pasca Perang Dunia II yang berlandaskan pertarungan ideologi, bukan bentrokan militer langsung. Dunia terbelah menjadi dua kutub raksasa yang saling berlomba dalam teknologi nuklir, eksploitasi antariksa (Space Race), dan perang proksi (Proxy War). Buat kamu yang butuh pemahaman cepat tanpa pusing membaca buku tebal, TugasMu sebagai teman pintar belajar akan membedahnya.\n\n## Akar Konflik Ideologi\nPerang Dingin mempresentasikan dua sistem kehidupan yang tidak bisa disatukan:\n- **Blok Barat (Amerika Serikat):** Mengusung ideologi Demokrasi Liberal dan sistem ekonomi Kapitalis. Blok ini membentuk aliansi pertahanan militer bernama NATO (North Atlantic Treaty Organization).\n- **Blok Timur (Uni Soviet):** Mengusung ideologi Komunis-Sosialis dengan sistem ekonomi terpimpin (terpusat). Sebagai tandingan, mereka membentuk aliansi pertahanan Pakta Warsawa.\n\nMeski disebut "dingin" karena AS dan Uni Soviet tidak pernah saling tembak secara langsung, mereka mendanai perang saudara di negara-negara dunia ketiga untuk menanamkan pengaruhnya. Contoh perang proksi ini adalah Perang Korea (membelah Korea Utara dan Selatan) serta Perang Vietnam.\n\n## Peran Strategis Indonesia\nDi tengah polarisasi dunia yang memaksa negara-negara memilih kubu, Indonesia di bawah kepemimpinan Presiden Soekarno mengambil jalan independen melalui kebijakan **Politik Luar Negeri Bebas Aktif**.\n\n- **Bebas:** Tidak memihak atau terikat pada Blok Barat maupun Blok Timur.\n- **Aktif:** Terlibat proaktif dalam menciptakan perdamaian dunia.\n\nManifestasi dari kebijakan ini adalah keberhasilan Indonesia memprakarsai Konferensi Asia-Afrika (KAA) di Bandung pada tahun 1955. KAA inilah yang kemudian menjadi fondasi berdirinya **Gerakan Non-Blok (GNB)** pada 1961 (bersama India, Mesir, dan Yugoslavia) sebagai kekuatan alternatif negara-negara dunia ketiga.\n\nMeninjau sejarah perang dingin dan peran Indonesia membuktikan bahwa diplomasi negara berkembang bisa menyeimbangkan dominasi dua negara adidaya. Jika kamu diberi tugas membuat opini, Bimbingan AI bisa memberikan sudut pandang tambahan mengenai sisa-sisa Perang Dingin di era modern.'
  },
  {
    slug: 'masa-orde-baru-vs-era-reformasi-perubahan-sosial-politik',
    title: 'Masa Orde Baru vs Era Reformasi: Perubahan Politik dan Sosial',
    desc: 'Komparasi perbedaan sistem politik, kebebasan pers, otonomi daerah, dan kehidupan sosial antara masa Orde Baru dan era Reformasi.',
    content: 'Masa orde baru vs era reformasi mempresentasikan perbandingan antara sistem pemerintahan yang tersentralisasi secara otoriter dengan sistem demokrasi multipartai yang terdesentralisasi. Transisi berdarah pada tahun 1998 merombak total wajah hukum dan kebebasan sipil di Indonesia. Biar gampang dimengerti buat tugas perbandingan sejarah, TugasMu sebagai teman pintar belajar udah merangkum inti perubahannya.\n\n## 1. Kebebasan Pers dan Berekspresi\n- **Orde Baru:** Pers sangat dikontrol ketat oleh Departemen Penerangan. Media massa yang melontarkan kritik keras kepada pemerintah (seperti Majalah Tempo dan Detik) akan langsung dibredel (dicabut izin terbitnya). Kebebasan berkumpul dan berpendapat diawasi oleh aparat keamanan.\n- **Reformasi:** Kebebasan pers dijamin penuh oleh undang-undang. Departemen Penerangan dibubarkan oleh Presiden Gus Dur. Masyarakat bebas menyuarakan kritik, berdemonstrasi, dan mendirikan serikat buruh tanpa takut tindakan represif instan.\n\n## 2. Sistem Kepartaian dan Pemilu\n- **Orde Baru:** Sistem politik disederhanakan melalui fusi partai (hanya boleh ada Golkar, PPP, dan PDI). Pemilu tidak berjalan secara langsung (presiden dipilih oleh MPR yang anggotanya didominasi militer dan pejabat yang ditunjuk).\n- **Reformasi:** Mengadopsi sistem multipartai secara bebas. Sejak amandemen konstitusi tahun 2004, presiden, kepala daerah (Pilkada), hingga anggota dewan dipilih secara langsung oleh rakyat dalam pemilu yang diawasi lembaga independen (KPU dan Bawaslu).\n\n## 3. Desentralisasi vs Sentralisasi\n- **Orde Baru:** Pembangunan bersifat Jawasentris dan kewenangan mutlak berada di pemerintah pusat (Jakarta). Daerah-daerah penghasil sumber daya alam besar (seperti Aceh dan Papua) disedot kekayaannya tanpa mendapat bagi hasil yang adil.\n- **Reformasi:** Diberlakukannya Otonomi Daerah melalui UU No. 22 Tahun 1999. Pemerintah daerah diberikan hak untuk mengatur anggaran dan pembangunannya sendiri secara mandiri (desentralisasi), guna mencegah ketimpangan ekonomi antarpulau.\n\n## 4. Dwifungsi ABRI\n- **Orde Baru:** Militer (ABRI) memiliki peran ganda (dwifungsi) sebagai alat pertahanan negara sekaligus kekuatan sosial-politik (diberi jatah kursi di DPR/MPR tanpa pemilu, serta menjabat posisi kepala daerah).\n- **Reformasi:** Dwifungsi ABRI dihapus secara resmi. Militer (kini TNI) dikembalikan ke barak murni sebagai alat pertahanan negara, dan polisi dipisahkan khusus menangani keamanan sipil.\n\nMenganalisis masa orde baru vs era reformasi membuktikan betapa krusialnya amandemen UUD 1945 dalam membatasi kekuasaan eksekutif agar tidak melahirkan tirani baru. Manfaatkan Bimbingan AI untuk mengembangkan argumen komparatifmu di esai sejarah.'
  }
];

const DIR = path.join(__dirname, '../frontend/src/content/blog/sejarah');

entries.forEach(entry => {
  const fileContent = `---
title: "${entry.title}"
description: "${entry.desc}"
date: "2026-10-01T04:10:00Z"
kategori: "sejarah"
---

${entry.content}
`;
  const filePath = path.join(DIR, `${entry.slug}.mdx`);
  fs.writeFileSync(filePath, fileContent);
  console.log(`Generated: ${entry.slug}`);
});
