const fs = require('fs');
const path = require('path');

const entries = [
  {
    slug: 'sistem-hukum-dan-peradilan-nasional-indonesia',
    title: 'Sistem Hukum dan Peradilan Nasional di Indonesia',
    desc: 'Pengertian hukum positif di Indonesia, jenis-jenis penggolongan hukum, serta hierarki lembaga peradilan dari tingkat pertama hingga MA.',
    content: 'Sistem hukum dan peradilan nasional di Indonesia dirancang berdasarkan asas negara hukum (Rechtsstaat) sebagaimana tertuang dalam Pasal 1 ayat (3) UUD 1945. Hukum tidak hanya berfungsi menghukum, tetapi juga menciptakan ketertiban sosial yang berkeadilan. Buat kamu yang ingin masuk Fakultas Hukum atau sekadar ingin nilai PPKn memuaskan, TugasMu sebagai teman pintar belajar akan membedah fondasi dasar sistem peradilan kita.\n\n## Penggolongan Hukum di Indonesia\nHukum di Indonesia sangat luas dan digolongkan berdasarkan wujud, ruang, hingga masalah yang diaturnya:\n- **Hukum Publik (Pidana):** Hukum yang mengatur hubungan antara negara dengan individu yang menyangkut kepentingan umum. Contohnya adalah KUHP (Kitab Undang-Undang Hukum Pidana) untuk kasus pencurian, pembunuhan, atau korupsi.\n- **Hukum Privat (Perdata):** Hukum yang mengatur hubungan antar-individu (perseorangan) dan menitikberatkan pada kepentingan pribadi. Contohnya adalah kasus perceraian, sengketa warisan, atau hutang-piutang.\n- **Hukum Tata Negara:** Aturan mengenai struktur negara dan administrasi pemerintahan.\n\n## Struktur Lembaga Peradilan\nBerdasarkan Undang-Undang Kekuasaan Kehakiman, sistem peradilan di Indonesia memiliki hierarki atau tingkatan untuk menjamin keadilan yang berlapis:\n1. **Pengadilan Negeri (Tingkat Pertama):** Berkedudukan di tingkat kabupaten/kota. Ini adalah tempat pertama kali sebuah kasus pidana/perdata disidangkan.\n2. **Pengadilan Tinggi (Tingkat Banding):** Berkedudukan di ibu kota provinsi. Jika ada pihak yang merasa tidak puas dengan vonis di Pengadilan Negeri, mereka berhak mengajukan memori banding ke Pengadilan Tinggi.\n3. **Mahkamah Agung (Tingkat Kasasi):** Berkedudukan di Jakarta. MA adalah lembaga peradilan tertinggi di Indonesia. MA berhak mengabulkan atau menolak permohonan kasasi atas putusan Pengadilan Tinggi, serta memiliki wewenang untuk meninjau kembali (PK) sebuah kasus apabila ditemukan bukti baru (novum).\n\nSelain peradilan umum, Indonesia juga memiliki pengadilan khusus seperti Pengadilan Agama, Pengadilan Militer, dan Pengadilan Tata Usaha Negara (PTUN). Menghafal hierarki sistem hukum dan peradilan ini akan membantu kamu memahami berita-berita hukum nasional di televisi. Jika kamu butuh contoh studi kasus pengadilan, fitur bimbingan AI siap membantu merangkumkannya.'
  },
  {
    slug: 'perbedaan-pelanggaran-hukum-dan-pelanggaran-etika',
    title: 'Perbedaan Pelanggaran Hukum dan Pelanggaran Etika',
    desc: 'Pemahaman krusial mengenai batas antara pelanggaran moral (etika) dengan pelanggaran norma hukum yang berlaku secara formal.',
    content: 'Perbedaan pelanggaran hukum dan pelanggaran etika berpusat pada sifat dasar norma, sumber aturan, serta bentuk sanksi yang dijatuhkan kepada pelanggarnya. Seringkali masyarakat bingung membedakan antara perbuatan yang "tidak sopan" dengan perbuatan yang "ilegal". Biar tugas analisis PPKn kamu tidak melenceng, mari kita bandingkan secara tegas menggunakan panduan dari Bimbingan AI TugasMu sebagai teman pintar belajar.\n\n## 1. Sumber dan Sifat Aturan\n- **Pelanggaran Etika (Moral):** Bersumber dari kebiasaan, adat istiadat masyarakat lokal, agama, atau kode etik sebuah profesi (misalnya Kode Etik Kedokteran/Jurnalistik). Aturannya bersifat tidak tertulis secara formal kenegaraan, namun disepakati oleh kelompok tertentu.\n- **Pelanggaran Hukum:** Bersumber dari undang-undang positif yang dirumuskan, disahkan, dan diberlakukan secara resmi oleh badan legislatif negara (DPR). Aturannya bersifat tertulis, mengikat secara absolut, dan berlaku memaksa bagi seluruh wilayah NKRI.\n\n## 2. Karakteristik Sanksi\n- **Sanksi Pelanggaran Etika:** Bentuk hukumannya bersifat non-fisik (sanksi sosial). Pelanggar akan mendapatkan cemoohan, dikucilkan oleh masyarakat, hilangnya kepercayaan, teguran profesi, hingga rasa penyesalan/rasa bersalah dari dalam diri. (Contoh: Berbicara kasar kepada orang tua, memotong antrean).\n- **Sanksi Pelanggaran Hukum:** Bentuk hukumannya sangat tegas, nyata, dan dapat dipaksakan oleh aparat negara (polisi, jaksa, hakim). Sanksinya berupa denda materiel, penyitaan aset, kurungan penjara, hingga hukuman mati. (Contoh: Mengemudi tanpa SIM, melakukan penipuan *online*, mencuri dana perusahaan).\n\n## Irisan antara Etika dan Hukum\nMeski berbeda, hukum dan etika sering kali saling tumpang tindih. Ada perbuatan yang melanggar hukum sekaligus melanggar etika (misalnya pembunuhan: secara etika itu sangat keji, secara hukum pelakunya akan dipenjara seumur hidup).\n\nNamun, ada perbuatan yang melanggar etika tapi tidak melanggar hukum pidana. Contoh: Seorang karyawan mengundurkan diri secara mendadak tanpa pamit ke perusahaan. Secara etika bisnis itu sangat buruk, namun ia tidak bisa dipenjara oleh polisi (kecuali melanggar klausul kontrak perdata).\n\nMemahami perbedaan batasan ini adalah kunci dalam mendiagnosis masalah sosial. Jika kamu menemukan kasus di berita, manfaatkan *tools* pembuat kesimpulan dari Bimbingan AI untuk mengategorikannya secara tepat.'
  },
  {
    slug: 'peran-penting-indonesia-dalam-hubungan-internasional',
    title: 'Peran Penting Indonesia dalam Hubungan Internasional',
    desc: 'Analisis partisipasi aktif Indonesia dalam politik luar negeri bebas aktif melalui keanggotaan PBB, ASEAN, dan Gerakan Non-Blok.',
    content: 'Peran penting Indonesia dalam hubungan internasional merupakan mandat langsung dari alinea keempat Pembukaan UUD 1945, yaitu ikut melaksanakan ketertiban dunia yang berdasarkan kemerdekaan, perdamaian abadi, dan keadilan sosial. Indonesia tidak pernah menjadi negara tertutup. Bersama TugasMu sebagai teman pintar belajar, mari kita telusuri bagaimana negara kita memainkan perannya di atas papan catur geopolitik dunia.\n\n## Prinsip Politik Luar Negeri Bebas Aktif\nFondasi diplomasi Indonesia dicetuskan oleh Mohammad Hatta, yaitu prinsip "Bebas Aktif". \n- **Bebas** berarti Indonesia tidak memihak (tidak terikat) kepada blok kekuatan militer mana pun di dunia (misalnya tidak ikut NATO milik Amerika atau Pakta Warsawa milik Uni Soviet).\n- **Aktif** berarti Indonesia tidak bersikap pasif, melainkan proaktif mengirimkan bantuan kemanusiaan dan meredakan konflik peperangan di negara lain.\n\n## Keterlibatan di Perserikatan Bangsa-Bangsa (PBB)\nIndonesia secara resmi menjadi anggota ke-60 PBB pada tanggal 28 September 1950. Kontribusi terbesarnya adalah pengiriman Pasukan Garuda (Kontingen Garuda). Sejak tahun 1957, pasukan militer Indonesia telah dikirim sebagai pasukan penjaga perdamaian PBB (*peacekeepers*) ke berbagai daerah konflik berdarah, seperti Kongo, Lebanon, dan Bosnia.\n\n## Peran Utama di ASEAN\nDi kawasan regional Asia Tenggara, Indonesia adalah "Kakak Tertua". Indonesia merupakan satu dari lima negara pemrakarsa berdirinya Association of Southeast Asian Nations (ASEAN) pada 8 Agustus 1967 melalui Deklarasi Bangkok. \nIndonesia sering bertindak sebagai mediator konflik regional, contohnya menjadi penengah dalam perang saudara di Kamboja dan memfasilitasi dialog damai antara pemerintah Filipina dengan kelompok pemberontak MNLF.\n\n## Pemrakarsa Gerakan Non-Blok (GNB)\nPuncak prestasi diplomasi Indonesia terjadi pada masa Perang Dingin. Melalui Konferensi Asia Afrika (KAA) di Bandung 1955, Indonesia memelopori lahirnya Gerakan Non-Blok, sebuah aliansi negara-negara berkembang yang menolak terseret dalam perang nuklir antara AS dan Uni Soviet.\n\nMengevaluasi peran penting Indonesia membuktikan bahwa diplomasi damai jauh lebih kuat daripada aliansi militer. Jika kamu mendapat tugas merangkum resolusi PBB yang melibatkan Indonesia, gunakan Bimbingan AI untuk mendapatkan ringkasan yang akurat.'
  },
  {
    slug: 'contoh-kasus-pelanggaran-ham-berat-di-indonesia',
    title: 'Contok Kasus Pelanggaran HAM Berat di Indonesia',
    desc: 'Bedah sejarah contoh-contoh kasus pelanggaran Hak Asasi Manusia (HAM) berat di Indonesia seperti Trisakti 1998 dan kasus Munir.',
    content: 'Contoh kasus pelanggaran HAM berat di Indonesia menjadi sejarah kelam bangsa yang terus dievaluasi agar tidak terulang kembali di masa depan. Berbeda dengan pelanggaran HAM ringan (seperti pencemaran nama baik), pelanggaran HAM berat meliputi genosida atau kejahatan kemanusiaan yang terencana secara sistematis. Buat kamu yang ingin menyusun makalah PPKn terkait ini, TugasMu sebagai teman pintar belajar telah merangkum beberapa kasus paling disorot.\n\n## 1. Tragedi Penembakan Mahasiswa Trisakti (1998)\nKasus ini merupakan titik balik runtuhnya Orde Baru. Pada 12 Mei 1998, ribuan mahasiswa Universitas Trisakti Jakarta menggelar demonstrasi damai menuntut Presiden Soeharto mundur akibat krisis ekonomi. \nSecara tiba-tiba, aparat keamanan menembakkan peluru tajam ke arah kerumunan massa yang menyebabkan empat mahasiswa gugur (Elang Mulia Lesmana, Hafidin Royan, Heri Hertanto, dan Hendriawan Sie). Hingga saat ini, dalang intelektual di balik perintah penembakan tersebut belum diadili secara tuntas.\n\n## 2. Kasus Pembunuhan Aktivis Munir (2004)\nMunir Said Thalib adalah seorang pejuang HAM yang vokal membela keluarga korban penculikan aktivis 1998. Pada 7 September 2004, Munir tewas diracun dengan arsenik saat berada di dalam penerbangan Garuda Indonesia dari Jakarta menuju Amsterdam. \nMeski sang eksekutor lapangan (Pollycarpus) telah dihukum penjara, namun dalang utama (aktor intelektual) yang memberikan perintah pembunuhan berencana tersebut masih menjadi misteri hukum di Indonesia.\n\n## 3. Tragedi Semanggi I dan II (1998-1999)\nMenyusul tragedi Trisakti, rentetan kekerasan aparat kembali terjadi saat mahasiswa menolak Sidang Istimewa MPR dan dwifungsi ABRI. Tragedi Semanggi I (November 1998) menewaskan belasan warga sipil, dilanjutkan dengan Tragedi Semanggi II (September 1999) yang kembali memakan korban jiwa mahasiswa UI. Kasus ini mengendap bertahun-tahun di Kejaksaan Agung karena perdebatan politik di DPR.\n\n## Mengapa Sulit Diselesaikan?\nPenyelesaian kasus HAM masa lalu sering kali terbentur oleh hilangnya barang bukti, masa kedaluwarsa tuntutan, hingga intervensi aktor politik kuat yang masih berkuasa. Pemerintah kini mencoba jalur penyelesaian *non-yudisial* (pemulihan hak korban tanpa pengadilan pidana). Jika kamu ingin memperdalam topik ini, Bimbingan AI dapat merangkumkan landasan hukum dari UU Pengadilan HAM yang relevan.'
  },
  {
    slug: 'konsep-otonomi-daerah-dan-desentralisasi-indonesia',
    title: 'Konsep Otonomi Daerah dan Desentralisasi di Indonesia',
    desc: 'Pengertian desentralisasi, asas otonomi daerah, serta pembagian urusan pemerintahan antara pusat dan daerah di era Reformasi.',
    content: 'Konsep otonomi daerah dan desentralisasi di Indonesia lahir sebagai koreksi total terhadap sistem sentralisasi (kekuasaan mutlak di Jakarta) pada era Orde Baru yang memicu ketidakadilan ekonomi antarpulau. Bagi kamu yang sering bingung mengapa daerah punya anggaran sendiri, Bimbingan AI TugasMu sebagai teman pintar belajar akan membedah prinsip dasar tata kelola pemerintahan yang baru ini.\n\n## Pengertian Desentralisasi dan Otonomi\nBerdasarkan UU Pemerintahan Daerah, **Desentralisasi** adalah penyerahan urusan pemerintahan oleh Pemerintah Pusat kepada daerah otonom (provinsi/kabupaten/kota) untuk mengatur urusannya sendiri.\nAkibat dari desentralisasi ini lahirlah **Otonomi Daerah**, yaitu hak, wewenang, dan kewajiban daerah untuk mengurus rumah tangganya sendiri sesuai dengan peraturan perundang-undangan. Tujuannya adalah mempercepat kesejahteraan rakyat di pelosok dan memaksimalkan potensi sumber daya alam lokal tanpa harus menunggu instruksi dari Jakarta.\n\n## Pembagian Urusan Pemerintahan\nMeski daerah memiliki kebebasan mengatur anggarannya (APBD), Indonesia tetaplah Negara Kesatuan (bukan negara serikat/federal). Oleh karena itu, ada **Enam Urusan Absolut** yang tetap dikuasai sepenuhnya oleh Pemerintah Pusat, yaitu:\n1. **Politik Luar Negeri** (Mengangkat duta besar, meratifikasi perjanjian internasional).\n2. **Pertahanan** (Mengelola TNI, pembelian persenjataan militer).\n3. **Keamanan** (Mengelola Polri, ketertiban umum nasional).\n4. **Yustisi / Peradilan** (Mengelola hakim, jaksa, dan lembaga pemasyarakatan).\n5. **Moneter dan Fiskal Nasional** (Mencetak uang, mengatur nilai tukar mata uang, menetapkan pajak nasional).\n6. **Agama** (Mengatur hari libur keagamaan, penyelenggaraan haji).\n\n## Urusan Konkuren (Bagi Hasil)\nDi luar enam urusan absolut tersebut, sisanya disebut urusan konkuren (dibagi antara pusat dan daerah). Contohnya adalah pendidikan (daerah berhak mengelola SMA/SMK), kesehatan (membangun RSUD), dan pariwisata lokal.\n\nMemahami konsep otonomi daerah akan membantu kamu mengerti mengapa standar UMR (Upah Minimum Regional) di setiap provinsi bisa berbeda-beda. Gunakan *tools* pembuat rangkuman TugasMu jika ingin meringkas pasal-pasal undang-undang pemda yang panjang untuk presentasi sekolah.'
  }
];

const DIR = path.join(__dirname, '../frontend/src/content/blog/ppkn');

entries.forEach(entry => {
  const fileContent = `---
title: "${entry.title}"
description: "${entry.desc}"
date: "2026-10-01T04:30:00Z"
kategori: "ppkn"
---

${entry.content}
`;
  const filePath = path.join(DIR, `${entry.slug}.mdx`);
  fs.writeFileSync(filePath, fileContent);
  console.log(`Generated: ${entry.slug}`);
});
